name: 'Release Github'

on:
  workflow_dispatch:
  push:
    paths:
      - 'content/**'
      - 'Shotgun.Templates.csproj'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - id: generate-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true         

      - name: Run dotnet pack
        run: |
          VERSION=${{ steps.generate-version.outputs.version }}
          dotnet pack -c Release -p:PackageVersion=${VERSION#v}

      - name: Push to Github Packages
        run: |
          dotnet nuget add source --username shotgun-templates --password ${{ secrets.GH_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/shotgun-templates/index.json"
          dotnet nuget push bin/Release/*.nupkg -k ${{ secrets.GH_PAT }} -s 'github'
      
      - name: Delete older versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: Shotgun.Templates
          package-type: nuget
          min-versions-to-keep: 5
          token: ${{ secrets.GH_PAT }}
      
