name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run dotnet pack
        run: |
          TAG=${{ github.ref_name }}
          dotnet pack -c Release -p:PackageVersion=${TAG#v}

      - name: Push package to Nuget
        run: dotnet nuget push bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      
